<?php

namespace Dcs\Recette\database\seeders;

use Illuminate\Database\Seeder;

class RctPayementsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('rct_payements')->delete();

        \DB::table('rct_payements')->insert(array (
            0 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 20,
                'created_at' => '2020-07-23 22:39:22',
                'date' => '2020-07-22',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 134,
                'libelle' => 'payem1',
                'libelle_ar' => NULL,
                'mois_id' => 8,
                'montant' => '20080',
                'montant_arriere' => '0',
                'ref_commune_id' => 1,
                'updated_at' => '2020-07-23 22:39:22',
            ),
            1 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 21,
                'created_at' => '2020-07-24 10:06:50',
                'date' => '2020-07-24',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 148,
                'libelle' => 'Suspendre Septembre',
                'libelle_ar' => 'Suspendre Septembre',
                'mois_id' => 9,
                'montant' => '0',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2020-07-24 10:06:50',
            ),
            2 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 21,
                'created_at' => '2020-07-24 10:06:51',
                'date' => '2020-07-24',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 149,
                'libelle' => 'Suspendre Octobre',
                'libelle_ar' => 'Suspendre Octobre',
                'mois_id' => 10,
                'montant' => '0',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2020-07-24 10:06:51',
            ),
            3 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 21,
                'created_at' => '2020-07-24 10:06:52',
                'date' => '2020-07-24',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 150,
                'libelle' => 'Suspendre Novembre',
                'libelle_ar' => 'Suspendre Novembre',
                'mois_id' => 11,
                'montant' => '0',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2020-07-24 10:06:52',
            ),
            4 =>
            array (
                'annee' => '2019',
                'contribuable_id' => 24,
                'created_at' => '2020-07-28 12:36:57',
                'date' => '2020-07-29',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 153,
                'libelle' => 'tranche 1',
                'libelle_ar' => NULL,
                'mois_id' => 7,
                'montant' => '2',
                'montant_arriere' => '498',
                'ref_commune_id' => 0,
                'updated_at' => '2020-07-28 12:38:01',
            ),
            5 =>
            array (
                'annee' => '2019',
                'contribuable_id' => 24,
                'created_at' => '2020-07-28 12:38:01',
                'date' => '2020-07-26',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 154,
                'libelle' => 'tr2',
                'libelle_ar' => NULL,
                'mois_id' => 7,
                'montant' => '500',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2020-07-28 12:38:01',
            ),
            6 =>
            array (
                'annee' => '2019',
                'contribuable_id' => 24,
                'created_at' => '2020-07-28 12:38:02',
                'date' => '2020-07-26',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 155,
                'libelle' => 'tr2',
                'libelle_ar' => NULL,
                'mois_id' => 8,
                'montant' => '500',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2020-07-28 12:38:02',
            ),
            7 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 21,
                'created_at' => '2020-07-28 13:08:31',
                'date' => '2020-08-09',
                'deleted_at' => NULL,
                'etat' => 2,
                'id' => 158,
                'libelle' => 'ddd',
                'libelle_ar' => NULL,
                'mois_id' => 1,
                'montant' => '69503',
                'montant_arriere' => '497',
                'ref_commune_id' => 0,
                'updated_at' => '2020-07-28 13:16:49',
            ),
            8 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 21,
                'created_at' => '2020-07-28 13:19:50',
                'date' => '2020-07-29',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 160,
                'libelle' => 'descr',
                'libelle_ar' => NULL,
                'mois_id' => 1,
                'montant' => '70000',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2020-07-28 13:19:50',
            ),
            9 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 23,
                'created_at' => '2020-07-28 13:40:50',
                'date' => '2020-07-29',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 161,
                'libelle' => '1ere tpaiement en 2020',
                'libelle_ar' => NULL,
                'mois_id' => 1,
                'montant' => '5000000',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2020-07-28 13:40:50',
            ),
            10 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 23,
                'created_at' => '2020-07-30 12:28:15',
                'date' => '2020-07-30',
                'deleted_at' => NULL,
                'etat' => 2,
                'id' => 162,
                'libelle' => 'PAIEMENT DDD',
                'libelle_ar' => NULL,
                'mois_id' => 2,
                'montant' => '300',
                'montant_arriere' => '4999700',
                'ref_commune_id' => 0,
                'updated_at' => '2020-07-30 12:28:15',
            ),
            11 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 28,
                'created_at' => '2020-11-05 09:29:36',
                'date' => '2020-11-09',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 163,
                'libelle' => 'mettou',
                'libelle_ar' => NULL,
                'mois_id' => 12,
                'montant' => '200',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2020-11-05 09:29:36',
            ),
            12 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 29,
                'created_at' => '2020-11-30 21:20:45',
                'date' => '2020-11-30',
                'deleted_at' => NULL,
                'etat' => 2,
                'id' => 164,
                'libelle' => 'hghg',
                'libelle_ar' => NULL,
                'mois_id' => 12,
                'montant' => '330',
                'montant_arriere' => '70',
                'ref_commune_id' => 0,
                'updated_at' => '2020-11-30 21:22:56',
            ),
            13 =>
            array (
                'annee' => '2019',
                'contribuable_id' => 30,
                'created_at' => '2020-11-30 22:31:25',
                'date' => '2020-11-30',
                'deleted_at' => NULL,
                'etat' => 2,
                'id' => 168,
                'libelle' => 'Premier paiement',
                'libelle_ar' => NULL,
                'mois_id' => 4,
                'montant' => '200',
                'montant_arriere' => '200',
                'ref_commune_id' => 0,
                'updated_at' => '2020-11-30 22:31:25',
            ),
            14 =>
            array (
                'annee' => '2019',
                'contribuable_id' => 32,
                'created_at' => '2021-12-12 17:29:06',
                'date' => '2021-12-12',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 169,
                'libelle' => 'Paiement taxe communale',
                'libelle_ar' => NULL,
                'mois_id' => 12,
                'montant' => '400',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2021-12-12 17:29:06',
            ),
            15 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 33,
                'created_at' => '2023-04-28 10:22:38',
                'date' => '2023-04-28',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 170,
                'libelle' => 'eds',
                'libelle_ar' => NULL,
                'mois_id' => 5,
                'montant' => '500',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-04-28 10:22:38',
            ),
            16 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 33,
                'created_at' => '2023-04-28 10:23:19',
                'date' => '2023-04-28',
                'deleted_at' => NULL,
                'etat' => 2,
                'id' => 171,
                'libelle' => 'GGGH',
                'libelle_ar' => NULL,
                'mois_id' => 6,
                'montant' => '400',
                'montant_arriere' => '100',
                'ref_commune_id' => 0,
                'updated_at' => '2023-04-28 10:23:19',
            ),
            17 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 34,
                'created_at' => '2023-05-06 18:00:42',
                'date' => '2023-05-06',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 172,
                'libelle' => 'Test',
                'libelle_ar' => NULL,
                'mois_id' => 5,
                'montant' => '400',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-06 18:00:42',
            ),
            18 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 34,
                'created_at' => '2023-05-06 18:15:37',
                'date' => '2023-05-06',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 173,
                'libelle' => 'Ebba',
                'libelle_ar' => NULL,
                'mois_id' => 6,
                'montant' => '400',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-06 18:15:37',
            ),
            19 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 34,
                'created_at' => '2023-05-06 18:21:18',
                'date' => '2023-06-04',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 174,
                'libelle' => 'Ebba5',
                'libelle_ar' => NULL,
                'mois_id' => 7,
                'montant' => '400',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-06 18:21:18',
            ),
            20 =>
            array (
                'annee' => '2023',
                'contribuable_id' => 38,
                'created_at' => '2023-05-07 10:53:38',
                'date' => '2023-05-07',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 180,
                'libelle' => 'jkrf`l;`',
                'libelle_ar' => NULL,
                'mois_id' => 5,
                'montant' => '400',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-07 10:53:38',
            ),
            21 =>
            array (
                'annee' => '2023',
                'contribuable_id' => 38,
                'created_at' => '2023-05-07 10:54:19',
                'date' => '2023-05-27',
                'deleted_at' => NULL,
                'etat' => 2,
                'id' => 181,
                'libelle' => 'Ebbavb',
                'libelle_ar' => NULL,
                'mois_id' => 6,
                'montant' => '100',
                'montant_arriere' => '300',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-07 10:54:19',
            ),
            22 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 20,
                'created_at' => '2023-05-11 11:19:02',
                'date' => '2023-05-11',
                'deleted_at' => NULL,
                'etat' => 2,
                'id' => 183,
                'libelle' => 'DDDD',
                'libelle_ar' => NULL,
                'mois_id' => 9,
                'montant' => '1700',
                'montant_arriere' => '-1300',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-11 11:19:02',
            ),
            23 =>
            array (
                'annee' => '2019',
                'contribuable_id' => 30,
                'created_at' => '2023-05-11 13:58:49',
                'date' => '2023-05-11',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 186,
                'libelle' => 'Suspendu Mai',
                'libelle_ar' => 'Suspendu Mai',
                'mois_id' => 5,
                'montant' => '0',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-11 13:58:49',
            ),
            24 =>
            array (
                'annee' => '2019',
                'contribuable_id' => 30,
                'created_at' => '2023-05-11 13:58:51',
                'date' => '2023-05-11',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 187,
                'libelle' => 'Suspendu Juillet',
                'libelle_ar' => 'Suspendu Juillet',
                'mois_id' => 7,
                'montant' => '0',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-11 13:58:51',
            ),
            25 =>
            array (
                'annee' => '2019',
                'contribuable_id' => 24,
                'created_at' => '2023-05-11 14:17:58',
                'date' => '2023-05-11',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 188,
                'libelle' => 'Suspendu Septembre',
                'libelle_ar' => 'Suspendu Septembre',
                'mois_id' => 9,
                'montant' => '0',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-11 14:17:58',
            ),
            26 =>
            array (
                'annee' => '2019',
                'contribuable_id' => 24,
                'created_at' => '2023-05-11 14:17:59',
                'date' => '2023-05-11',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 189,
                'libelle' => 'Suspendu Octobre',
                'libelle_ar' => 'Suspendu Octobre',
                'mois_id' => 10,
                'montant' => '0',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-11 14:17:59',
            ),
            27 =>
            array (
                'annee' => '2019',
                'contribuable_id' => 24,
                'created_at' => '2023-05-11 14:18:01',
                'date' => '2023-05-11',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 190,
                'libelle' => 'Suspendu Novembre',
                'libelle_ar' => 'Suspendu Novembre',
                'mois_id' => 11,
                'montant' => '0',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-11 14:18:01',
            ),
            28 =>
            array (
                'annee' => '2019',
                'contribuable_id' => 24,
                'created_at' => '2023-05-11 14:18:02',
                'date' => '2023-05-11',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 191,
                'libelle' => 'Suspendu Décembre',
                'libelle_ar' => 'Suspendu Décembre',
                'mois_id' => 12,
                'montant' => '0',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-11 14:18:02',
            ),
            29 =>
            array (
                'annee' => '2023',
                'contribuable_id' => 35,
                'created_at' => '2023-05-11 14:27:31',
                'date' => '2023-05-11',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 198,
                'libelle' => '700',
                'libelle_ar' => NULL,
                'mois_id' => 12,
                'montant' => '400',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-11 14:27:31',
            ),
            30 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 26,
                'created_at' => '2023-05-12 09:36:00',
                'date' => '2023-05-05',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 201,
                'libelle' => 'Ebba2',
                'libelle_ar' => NULL,
                'mois_id' => 1,
                'montant' => '500',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-12 09:36:00',
            ),
            31 =>
            array (
                'annee' => '2023',
                'contribuable_id' => 36,
                'created_at' => '2023-05-15 13:58:32',
                'date' => '2023-05-17',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 202,
                'libelle' => 'Testbn',
                'libelle_ar' => NULL,
                'mois_id' => 5,
                'montant' => '300',
                'montant_arriere' => '300',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-16 10:05:04',
            ),
            32 =>
            array (
                'annee' => '2023',
                'contribuable_id' => 37,
                'created_at' => '2023-05-15 15:58:53',
                'date' => '2023-05-15',
                'deleted_at' => NULL,
                'etat' => 2,
                'id' => 203,
                'libelle' => 'PAyemnt tes',
                'libelle_ar' => NULL,
                'mois_id' => 5,
                'montant' => '400',
                'montant_arriere' => '200',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-15 15:58:53',
            ),
            33 =>
            array (
                'annee' => '2023',
                'contribuable_id' => 39,
                'created_at' => '2023-05-15 16:01:03',
                'date' => '2023-10-15',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 204,
                'libelle' => 'Test oct',
                'libelle_ar' => NULL,
                'mois_id' => 10,
                'montant' => '900',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-15 16:01:03',
            ),
            34 =>
            array (
                'annee' => '2023',
                'contribuable_id' => 39,
                'created_at' => '2023-05-15 16:22:36',
                'date' => '2023-05-15',
                'deleted_at' => NULL,
                'etat' => 2,
                'id' => 207,
                'libelle' => 'Education5225',
                'libelle_ar' => NULL,
                'mois_id' => 11,
                'montant' => '300',
                'montant_arriere' => '600',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-15 16:22:36',
            ),
            35 =>
            array (
                'annee' => '2023',
                'contribuable_id' => 39,
                'created_at' => '2023-05-15 16:27:20',
                'date' => '2023-05-15',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 209,
                'libelle' => 'Suspendu Décembre',
                'libelle_ar' => 'Suspendu Décembre',
                'mois_id' => 12,
                'montant' => '0',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-15 16:27:20',
            ),
            36 =>
            array (
                'annee' => '2023',
                'contribuable_id' => 35,
                'created_at' => '2023-05-16 13:42:34',
                'date' => '2023-05-18',
                'deleted_at' => NULL,
                'etat' => 2,
                'id' => 211,
                'libelle' => 'Ebba4',
                'libelle_ar' => NULL,
                'mois_id' => 5,
                'montant' => '300',
                'montant_arriere' => '100',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-16 13:42:34',
            ),
            37 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 40,
                'created_at' => '2023-05-17 17:15:48',
                'date' => '2023-05-26',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 213,
                'libelle' => 'jmkkm',
                'libelle_ar' => NULL,
                'mois_id' => 6,
                'montant' => '300',
                'montant_arriere' => '300',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-17 17:16:49',
            ),
            38 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 40,
                'created_at' => '2023-05-17 17:23:22',
                'date' => '2023-05-18',
                'deleted_at' => NULL,
                'etat' => 2,
                'id' => 216,
                'libelle' => 'Ebba4754',
                'libelle_ar' => NULL,
                'mois_id' => 7,
                'montant' => '200',
                'montant_arriere' => '400',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-17 17:23:22',
            ),
            39 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 41,
                'created_at' => '2023-05-17 17:26:39',
                'date' => '2023-03-01',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 217,
                'libelle' => 'Ebba,m',
                'libelle_ar' => NULL,
                'mois_id' => 3,
                'montant' => '400',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-17 17:26:39',
            ),
            40 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 41,
                'created_at' => '2023-05-17 17:26:39',
                'date' => '2023-03-01',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 219,
                'libelle' => 'Ebba,m',
                'libelle_ar' => NULL,
                'mois_id' => 5,
                'montant' => '100',
                'montant_arriere' => '300',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-17 17:27:52',
            ),
            41 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 41,
                'created_at' => '2023-05-17 17:27:52',
                'date' => '2023-04-05',
                'deleted_at' => NULL,
                'etat' => 1,
                'id' => 220,
                'libelle' => 'Test5',
                'libelle_ar' => NULL,
                'mois_id' => 5,
                'montant' => '400',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-17 17:27:52',
            ),
            42 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 41,
                'created_at' => '2023-05-17 17:27:52',
                'date' => '2023-04-05',
                'deleted_at' => NULL,
                'etat' => 2,
                'id' => 221,
                'libelle' => 'Test5',
                'libelle_ar' => NULL,
                'mois_id' => 4,
                'montant' => '100',
                'montant_arriere' => '300',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-17 17:27:52',
            ),
            43 =>
            array (
                'annee' => '2020',
                'contribuable_id' => 26,
                'created_at' => '2023-05-17 23:39:54',
                'date' => '2023-05-17',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 222,
                'libelle' => 'Suspendu Février',
                'libelle_ar' => 'Suspendu Février',
                'mois_id' => 2,
                'montant' => '0',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-17 23:39:54',
            ),
            44 =>
            array (
                'annee' => '2023',
                'contribuable_id' => 35,
                'created_at' => '2023-05-19 12:28:59',
                'date' => '2023-05-19',
                'deleted_at' => NULL,
                'etat' => 3,
                'id' => 224,
                'libelle' => 'Suspendu Juin',
                'libelle_ar' => 'Suspendu Juin',
                'mois_id' => 6,
                'montant' => '0',
                'montant_arriere' => '0',
                'ref_commune_id' => 0,
                'updated_at' => '2023-05-19 12:28:59',
            ),
        ));


    }
}
